- name: Configure VLANs
  hosts: cml_testdevice
  connection: local
  gather_facts: no

  tasks:
    - name: load new acl into device
      ios_config:
        lines:
          - 10 permit ip host 10.10.67.10 any log
          - 20 permit ip host 10.10.67.20 any log
          - 30 permit ip host 10.10.67.30 any log
          - 40 permit ip host 10.10.67.40 any log
          - 50 permit ip host 10.10.67.50 any log
        parents: ip access-list extended test
        before: no ip access-list extended test
        match: exact
