[cml_testdevice]
10.10.67.xxx

[cml_testdevice:vars]
ansible_user=cisco
ansible_password=cisco
ansible_become_pass=cisco
ansible_connection=network_cli
ansible_network_os=ios
ansible_become=true
ansible_become_method=enable